
[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/night-plaid.jpg"
fragment = "night-plaid"
description = "A photo from the night before the century"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/plaid-pantry.jpg"
fragment = "plaid-pantry"
description = "Plaid Pantry, what a welcome sight!"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/bag-setup.jpg"
fragment = "bag-setup"
description = "I ran with trunk bag attached to my front rack, a handlebar bag, and a frame bag full of oui ouis"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/plaid-route.png"
fragment = "plaid-route"
description = "My Plaid Century route"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/welcome-to-gresham.jpg"
fragment = "welcome-to-gresham"
description = "Welcome to Gresham"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/another-plain-pantry.jpg"
fragment = "another-plain-pantry"
description = "A Plaid Pantry somewhere in Portland"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/donut-sticks.jpg"
fragment = "donut-sticks"
description = "Donuts on a stick to refuel"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/two-trucks-having-sex.jpg"
fragment = "two-trucks-having-sex"
description = "Two trucks having sex on Hayden Island"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/plaid-st-johns.jpg"
fragment = "plaid-st-johns"
description = "The St. John's Plaid Pantry, one of the control point stops"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/the-last-plaid.jpg"
fragment = "the-last-plaid"
description = "The last Plaid Pantry on the route, where so many stopped to revel in what they'd just done"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/helluva-crowd.jpg"
fragment = "helluva-crowd"
description = "A helluva crowd at the ending ceremonies at Laurelhurst Park"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/victory.jpg"
fragment = "victory"
description = "Sweet, sweet victory"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/plaid-patch.jpg"
fragment = "plaid-patch"
description = "A Plaid Century patch I got for completing my first century"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/plaid-receipt.jpg"
fragment = "plaid-receipt"
description = "My Proof of Plaid"

[[images]]
url = "https://assets.borzoi.horse/blog/plaid-century/blue-skies.jpg"
fragment = "blue-skies"
description = "Beautiful blue skies"

