[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/route (full).png"
fragment = "route-full"
description = "The full route I took, with each segment in a different color"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/route (downtown detail).png"
fragment = "route-downtown"
description = "The downtown detail of the route, split into waterfront and inner crows"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/route (west hills detail).png"
fragment = "route-west-hills"
description = "Detail on the west hills portion of the route, including the Pittock Mansion climb"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/the world of wildwood with bike.jpg"
description = "The World of Wildwood at St. Johns Library"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/the world of wildwood (detail).jpg"
fragment = "the-world-of-wildwood-detail"
description = "The World of Wildwood at St. Johns Library"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/the world of wildwood.jpg"
fragment = "the-world-of-wildwood"
description = "The World of Wildwood at St. Johns Library"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/heart of the forest.jpg"
fragment = "heart-of-the-forest"
description = "Heart of the Forest at Bird Alliance of Oregon"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/on a mission.jpg"
fragment = "on-a-mission"
description = "On a Mission at Pittock Mansion"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/sir timber cawthorne.jpg"
fragment = "sir-timber-cawthorne"
description = "Sir Timber Cawthorne at International Rose Test Garden"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/stash.jpg"
fragment = "stash"
description = "Stash at OHSU Knight Cancer Research Building"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/a murder huddle.jpg"
fragment = "a-murder-huddle"
description = "A Murder Huddle at OMSI"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/sir chester.jpg"
fragment = "sir-chester"
description = "Sir Chester at Lan SU Chinese Garden"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/vuela corazon.jpg"
fragment = "vuela-corazon"
description = "Vuela Corazon at North Park Blocks"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/rainbow trout bike.jpg"
fragment = "rainbow-trout-bike"
description = "Rainbow trout bike at North Park Blocks"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/be kind.jpg"
fragment = "be-kind"
description = "Be Kind at Car Wash Fountain"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/be kind 2.jpg"
fragment = "be-kind-2"
description = "Be Kind at Car Wash Fountain"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/bikes.jpg"
fragment = "bikes"
description = "Bikes at Car Wash Fountain Steps"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/do-nuts for portland.jpg"
fragment = "do-nuts-for-portland"
description = "Do-nuts for Portland at Ankeny Alley (Voodoo Donuts)"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/do-nuts for portland with bike.jpg"
fragment = "do-nuts-for-portland-with-bike"
description = "Do-nuts for Portland at Ankeny Alley (Voodoo Donuts)"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/watercolor crow.jpg"
fragment = "watercolor-crow"
description = "Watercolor Crow at Yamhill Pedestrian Plaza (SW 1st & Yamhill)"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/dusk.jpg"
fragment = "dusk"
description = "DUSK at Tom McCall Waterfront Park (SW Clay)"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/emergence.jpg"
fragment = "emergence"
description = "Emergence at Tom McCall Waterfront Park (Salmon Springs)"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/iridescence.jpg"
fragment = "iridescence"
description = "Iridescence at Tom McCall Waterfront Park (Burnside Bridge)"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/back alley flora.jpg"
fragment = "back-alley-flora"
description = "Back Alley Flora at N Broadway & N Flint"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/freak'n crow.jpg"
fragment = "freak'n-crow"
description = "Freak'n Crow at Jamison Square"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/midnight crow.jpg"
fragment = "midnight-crow"
description = "Midnight Crow at Couch Park"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/a crow of a different color.jpg"
fragment = "a-crow-of-a-different-color"
description = "A Crow of a Different Color at Lincoln High School"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/feather and flowers.jpg"
fragment = "feather-and-flowers"
description = "Feather and Flowers at Park Blocks"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/kindred spirits.jpg"
fragment = "kindred-spirits"
description = "Kindred Spirits at Keller Fountain"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/sakura hanami.jpg"
fragment = "sakura-hanami"
description = "Sakura Hanami at City Hall"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/oregon botanica.jpg"
fragment = "oregon-botanica"
description = "Oregon Botanica at Main Street Plaza"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/bloom.jpg"
fragment = "bloom"
description = "Bloom at Portland Art Museum East Plaza"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/as the crow flies (detail).jpg"
fragment = "as-the-crow-flies-(detail)"
description = "As the Crow Flies at Central Library"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/as the crow flies.jpg"
fragment = "as-the-crow-flies"
description = "As the Crow Flies at Central Library"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/flying fields forever.jpg"
fragment = "flying-fields-forever"
description = "Flying Fields Forever at Director Park"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/overgrowth.jpg"
fragment = "overgrowth"
description = "Overgrowth at Pioneer Courthouse Square"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/mirrorball messenger.jpg"
fragment = "mirrorball-messenger"
description = "Mirrorball Messenger at Darcelle XV Plaza"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/the shape of us.jpg"
fragment = "the-shape-of-us"
description = "The Shape of Us at Pod Plaza"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/paul birdyan.jpg"
fragment = "paul-birdyan"
description = "Paul Birdyan at Pride Plaza SW Harvey Milk"

[[images]]
url = "https://assets.borzoi.horse/blog/biking-the-crows/ravel.jpg"
fragment = "ravel"
description = "Ravel at NW 13th Ave & NW Everett"
