
[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/crepusculecat-boeuf.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/motel777-boeuf-bripe.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/crepusculecat-boeuf-coffee.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/beuf-sweater.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-badge.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-goat-hug.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-blushing.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-tamagotchi.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-head-pipe.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-long.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-nb-pride.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-pink-background.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-pumpkin-icon.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-scrungly.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-smile.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-tamagotchi-detail.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-wowzers.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/corruptedparadox-boeuf-godly.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/input-command-boeuf-head.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/verulence-boeuf-yoyo.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-doggy.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-headshot.jpg"