[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/crepusculecat-boeuf.png"
description = "artist: crepusculecat"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/motel777-boeuf-bripe.jpg"
description = "artist: motel777"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/crepusculecat-boeuf-coffee.jpg"
description = "artist: crepusculecat"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/beuf-sweater.png"
description = "artist: beaglescouts"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-badge.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/ink-boeuf-belly.png"
description = "artist: ink"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/samneukirch-boeuf-drippy.png"
description = "artist: Sam Neukirch"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-goat-hug.png"
description = "artist: beaglescouts"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-blushing.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-tamagotchi.png"
description = "artist: jinxsis"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-head-pipe.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/cloverhare-boeuf.jpg"
description = "artist: cloverhare"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-scrungly-posca.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/aspeneyes-boeuf-headshot.png"
description = "artist: aspeneyes"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/kikidoodles-boeuf.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-long.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-nb-pride.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-pink-background.png"
description = "artist: hauntedhomo"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/input-command-boeuf-doodle.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-pumpkin-icon.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-scrungly.png"
description = "artist: Tumult"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-smile.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-tamagotchi-detail.png"
description = "artist: jinxsis"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-wowzers.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-motel777-pride.jpg"
description = "artist: motel777"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-yoyo-icon.png"
description = "artist: Lyd Paige"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/corruptedparadox-boeuf-godly.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/input-command-boeuf-head.png"
description = "artist: dogstomp"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/verulence-boeuf-yoyo.jpg"
description = "artist: verulence"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/berndh01-boeuf.jpg"
description = "artist: berndh01"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/boeuf-headshot.jpg"