[[colors]]
name = "nose"
hexcode = "#2C2826"

[[colors]]
name = "eyes"
hexcode = "#244664"

[[colors]]
name = "coat (dark)"
hexcode = "#8C563B"

[[colors]]
name = "coat (light)"
hexcode = "#F3D7C9"

[[colors]]
name = "left ear piercing"
hexcode = "#F34CF0"

[[colors]]
name = "right ear piercing"
hexcode = "#5BBCF0"