[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/waterfall-corridor-map.jpg"
fragment = "waterfall-corridor-map"
description = "a map of the Historic Columbia River Highway between Corbett and Dodson"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/bates-lavendar-farm.jpg"
fragment = "bates-lavendar-farm"
description = "a short stop at Bates Lavendar Farm in Corbett"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/portland-womens-forum.jpg"
description = "a pretty view from the Portland Women's Forum State Scenic Viewpoint"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/vista-house.jpg"
fragment = "vista-house"
description = "a pretty view from the Vista House at Crown Point"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/railroad-stop-2.jpg"
description = "a little stop by a railroad signal near Wahkeena Falls"
fragment = "railroad-stop-2"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/railroad-stop.jpg"
description = "a little stop by a railroad signal near Wahkeena Falls"
fragment = "railroad-stop"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/horsetail-falls.jpg"
description = "Horsetail Falls"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/bike-suspension.jpg"
fragment = "bike-suspension"
description = "hammock suspension using the bike in place of a second tree"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/setting-up-the-hammock.jpg"
description = "photo of me setting up the hammock"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/hanging-in-the-hammock.jpg"
description = "my view from inside the hammock"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/bike-suspension-with-tarp.jpg"
fragment = "bike-suspension-with-tarp"
description = "hammock suspension including a tarp using the bike in place of a second tree"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/cat-lying-down-2.jpg"
description = "a cute cat that was wandering around the campsite"

[[images]]
url = "https://assets.borzoi.horse/blog/bikepacking-ainsworth-state-park/cat-lying-down.jpg"
description = "a cute cat that was wandering around the campsite"

