
[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/frame-bag-template-full.jpg"
fragment = "frame-bag-template-full"
description = "the full frame bag template"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/frame-bag-template-folded.jpg"
fragment = "frame-bag-template-folded"
description = "the frame bag template folded to make room for the water bottle"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/bag-on-mat-empty.jpg"
fragment = "bag-on-mat-empty"
description = "the finished bag"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/corner-detail.jpg"
fragment = "corner-detail"
description = "a detail shot of the corner showing the tape finish"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/grosgrain-detail.jpg"
fragment = "grosgrain-detail"
description = "a detail shot of the zipper"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/bag-on-mat-full.jpg"
fragment = "bag-on-mat-full"
description = "full of friends :3"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/oui-oui-from-front.jpg"
fragment = "oui-oui-from-front"
description = "bike suited up with the frame bag"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/oui-oui-from-side.jpg"
fragment = "oui-oui-from-side"
description = "bike suited up with the frame bag"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/bike-and-sky.jpg"
fragment = "bike-and-sky"
description = "bike suited up with the frame bag"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/sleepy-close-up.jpg"
fragment = "sleepy-close-up"
description = "sleepy wearing stinker's breeches"

[[images]]
url = "https://assets.borzoi.horse/blog/oui-oui-frame-bag/night.jpg"
fragment = "night"
description = "cool night-time photo of the bike :3"
