[[images]]
url = "https://assets.borzoi.horse/photos/honey-crisp/crips-big-stretch.jpg"
fragment = "crips-big-stretch"
description = "Honey Crisp doing a big stretch"

[[images]]
url = "https://assets.borzoi.horse/photos/honey-crisp/crisp-and-slug.jpg"
fragment = "crisp-and-slug"
description = "Honey Crisp enjoying her slug"

[[images]]
url = "https://assets.borzoi.horse/photos/honey-crisp/crisp-paw.jpg"
fragment = "crisp-paw"
description = "paws :3"

[[images]]
url = "https://assets.borzoi.horse/photos/honey-crisp/crisp-surprise.jpg"
fragment = "crisp-surprise"
description = "SURPRISE!!"

[[images]]
url = "https://assets.borzoi.horse/photos/honey-crisp/crisp-tongue-out.jpg"
fragment = "crisp-tongue-out"
description = "This is how she often is, tongue hanging out"

