[[images]]
url = "https://assets.borzoi.horse/photos/item-label/aplesto-on-the-rock.jpg"
fragment = "aplesto-on-the-rock"
description = "Aplesto sitting on a rock in a river"

[[images]]
url = "https://assets.borzoi.horse/photos/item-label/aplesto-slurp.jpg"
fragment = "aplesto-slurp"
description = "Aplesto enjoying a little slurp"

[[images]]
url = "https://assets.borzoi.horse/photos/item-label/fossil-potato.jpg"
fragment = "fossil-potato"
description = "A fossil oui oui among the potatoes"

[[images]]
url = "https://assets.borzoi.horse/photos/item-label/fruit-oops.jpg"
fragment = "fruit-oops"
description = "Fruit Oops looking adorable"

[[images]]
url = "https://assets.borzoi.horse/photos/item-label/lassie-octotree.jpg"
fragment = "lassie-octotree"
description = "Lassie hanging out at the octopus tree"

[[images]]
url = "https://assets.borzoi.horse/photos/item-label/oui-oui-frame-bag.JPG"
fragment = "oui-oui-frame-bag"
description = "Bike frame bag full of oui ouis"

[[images]]
url = "https://assets.borzoi.horse/photos/item-label/sleepy-friends.jpg"
fragment = "sleepy-friends"
description = "Sleepy and friends"

[[images]]
url = "https://assets.borzoi.horse/photos/item-label/tomato-surprise.jpg"
fragment = "tomato-surprise"
description = "Surprise tomato oui oui!!"