[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-floss-batshaped.png"
fragment = "candy-floss-batshaped"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-floss-candy.png"
fragment = "candy-floss-candy"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-floss-chibi.png"
fragment = "candy-floss-chibi"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-floss-dark.png"
fragment = "candy-floss-dark"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-floss-lollipop.png"
fragment = "candy-floss-lollipop"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-floss-posca.jpg"
fragment = "candy-floss-posca"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-floss-taco-horse.png"
fragment = "candy-floss-taco-horse"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-floss-verulence.png"
fragment = "candy-floss-verulence"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-lost-leg.jpg"
fragment = "candy-lost-leg"
description = ""

[[images]]
url = "https://assets.borzoi.horse/refs/candy-floss/candy-taco-thinking-about-tacos.png"
fragment = "candy-taco-thinking-about-tacos"
description = ""

