[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/boeuf-watercolor.jpg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/crepusculecat-boeuf.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/leafhoof-boeuf-sketch.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/input-command-boeuf.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/leafhoof-boeuf-stream.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/leafhoof-boeuf-bondage.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/achillean-god-boeuf.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/birdfood-boeuf.jpeg"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/cute-surprised-boeuf.png"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/pwyw pinup for flowbish.png"
