[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/boeuf-watercolor.jpg"
description = "artist: nasties9569"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/crepusculecat-boeuf.png"
description = "artist: crepusculecat"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/leafhoof-boeuf-sketch.png"
description = "artist: leafhoof"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/input-command-boeuf.png"
description = "artist: dogstomp"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/leafhoof-boeuf-stream.png"
description = "artist: leafhoof"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/leafhoof-boeuf-bondage.png"
description = "artist: leafhoof"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/enricksdisease-boeuf-tentacles.png"
description = "artist: enricksdisease"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/achillean-god-boeuf.png"
description = "artist: achilleangod"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/birdfood-boeuf.jpeg"
description = "artist: birdf00d"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/cute-surprised-boeuf.png"
description = "artist: RedFeral"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/pwyw pinup for flowbish.png"
description = "artist: dogflowers"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/cerbdraws-boeuf-magic-wand.jpg"
description = "artist: cerbdraws"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/julien-boeuf-goat-bondage.png"
description = "artist: julien"

[[images]]
url = "https://assets.borzoi.horse/refs/boeuf/nsfw/maim-boeuf-monster-fucker.png"
description = "artist: maim"
