[[entries]]
date = "2026-09-09T00:33:12.962Z"
name = "iris"
email = "iris@ink.horse"
message = "very cool webbed site by a very cool dog!! "

[[entries]]
name = "bish"
email = "flowbish@gmail.com"
date = "2026-09-09T00:17:55.542Z"
message = "testing out the guestbook!"